### ISSUE TITLE
Create real copies of dotfiles instead of symlinks

### ISSUE THREAD

**Issue by RickestRickSanchez** [RickestRickSanchez/dotmanager#13]
**Is your feature request related to a problem? Please describe.**
Sometimes programs don't follow symlinks.

**Describe the solution you'd like**
A `copy()` command is introduced that can be used to copy a file instead to link it. This needs to be explicitly stored in the installed file because a few exceptions need to be done for copies. For example it needs to be stored if the file changed. This could be achieved by storing the original together with its hash and comparing them later (like we do with DynamicFile).

**Comment by RickestRickSanchez** [comment]
> On a similar note, hard linking should be supported as well

I will create another ticket this. I guess hard links can't be use instead of copies to solve this issue, can they?

**Comment by AGitBoy** [comment]
actually its better to use hard links, as programs cannot tell the difference between a hard link and a copy, and we wouldn't have to sync it automatically.

-------- Original Message --------

**Comment by RickestRickSanchez** [comment]
> programs cannot tell the difference between a hard link and a copy

excellent! That was something I wasn't sure about it. In this case an option for using hard links would be already enough I guess. Closing this if you have no other objections.

**Comment by AGitBoy** [comment]
No other objections.
