### ISSUE TITLE
Man page

### ISSUE THREAD

**Issue by RickestRickSanchez** [RickestRickSanchez/dotmanager#18]
**Is your feature request related to a problem? Please describe.**
When the program gets packaged it should provide a man page.

**Describe the solution you'd like**
The man page doesn't need to explain all features of dotmanager. It should only explain the usage of dotmgr.py. For all further features of dotmanager the man page can point to the documentation.

**Comment by AGitBoy** [comment]
Should we use pandoc to generate the man pages?

**Comment by RickestRickSanchez** [comment]
Nice work, I will take a deeper look into this tomorrow!

**Comment by RickestRickSanchez** [comment]
I think doxygen is great, I wanted to generate the documentation anyway! So we can try doxy2man first and if it does not work or the result is to bad (it doesn't seem to be maintained anymore) I would go with pandoc and generate it from a markdown document.

**Comment by RickestRickSanchez** [comment]
For documentation I am using sphinx now. I will use it for the man page as well because it allows me to reuse the documentation, some dependencies and it will simplify the build.
